# Generated by Django 4.0 on 2022-01-03 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CasqueApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
